site_name: ScrapyMonitoramentoPreco
theme: material

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
